In [137]:
import tensorflow as tf

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('J:/Data science/data/Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [140]:
df.shape

(10000, 14)

In [141]:
x = df.iloc[: , 3:13]
y = df['Exited']

In [142]:
x.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [143]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [144]:
x = pd.get_dummies(x,drop_first=True)

In [145]:
x.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
0               1        101348.88                  0                0   
1               1        112542.58                  0                1   
2               0        113931.57                  0                0   
3               0         93826.63                  0                0   
4               1         79084.10                  0                1   

   Gender_Male  
0            0  
1            0  
2            0  
3            0  
4            0

In [146]:
from sklearn.model_selection import train_test_split

In [147]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=101)

In [148]:
from sklearn.preprocessing import StandardScaler

In [149]:
scaler = StandardScaler()
scaled_x_train = scaler.fit_transform(x_train)
scaled_x_test = scaler.transform(x_test)

In [150]:
scaled_x_train

array([[-1.45057405, -0.93156572,  1.37687702, ..., -0.57339125,
         1.75478035, -1.09759938],
       [ 0.76328696,  2.59755682, -0.34884172, ..., -0.57339125,
        -0.56987189,  0.91107923],
       [-0.43674985,  2.12064837, -1.38427296, ..., -0.57339125,
         1.75478035,  0.91107923],
       ...,
       [ 0.67018065,  0.21301457,  1.03173327, ...,  1.74400987,
        -0.56987189,  0.91107923],
       [-0.75744934, -0.64542065, -0.34884172, ..., -0.57339125,
        -0.56987189,  0.91107923],
       [ 0.01843653, -0.83618403, -1.03912921, ..., -0.57339125,
         1.75478035, -1.09759938]])

In [151]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(8, activation='relu' , name='hidden_1', input_shape=(11,)))
model.add(tf.keras.layers.Dense(6,activation='relu', name='hidden_2'))
model.add(tf.keras.layers.Dense(1,activation='sigmoid' , name='output'))

In [152]:
model.compile(optimizer='adam' ,
              loss='binary_ crossentropy' ,
              metrics=['accuracy'])

In [ ]:
y_tr

In [153]:
model.fit(scaled_x_train,y_train , epochs=100)

Epoch 1/100
219/219 [==============================] - 1s 854us/step - loss: 0.5752 - accuracy: 0.7414
Epoch 2/100
219/219 [==============================] - 0s 845us/step - loss: 0.4813 - accuracy: 0.7979
Epoch 3/100
219/219 [==============================] - 0s 867us/step - loss: 0.4582 - accuracy: 0.7979
Epoch 4/100
219/219 [==============================] - 0s 848us/step - loss: 0.4457 - accuracy: 0.7976
Epoch 5/100
219/219 [==============================] - 0s 831us/step - loss: 0.4373 - accuracy: 0.8023
Epoch 6/100
219/219 [==============================] - 0s 822us/step - loss: 0.4300 - accuracy: 0.8111
Epoch 7/100
219/219 [==============================] - 0s 834us/step - loss: 0.4234 - accuracy: 0.8156
Epoch 8/100
219/219 [==============================] - 0s 785us/step - loss: 0.4162 - accuracy: 0.8200
Epoch 9/100
219/219 [==============================] - 0s 880us/step - loss: 0.4097 - accuracy: 0.8249
Epoch 10/100
219/219 [==============================] - 0s 834us/step - l

In [154]:
y_pred = model.predict(scaled_x_test)

94/94 [==============================] - 0s 805us/step


In [155]:
y_pred

array([[0.027829  ],
       [0.03547804],
       [0.35875723],
       ...,
       [0.01311004],
       [0.5373604 ],
       [0.6037508 ]], dtype=float32)

In [156]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [ True],
       [ True]])

In [157]:
scaled_x_train.shape

(7000, 11)

In [158]:
model_2 = tf.keras.Sequential()
model_2.add(tf.keras.Input(shape=(11,)))
model_2.add(tf.keras.layers.Dense(8 , activation= 'relu', name ='hidden_1'))
model_2.add(tf.keras.layers.Dense(1 , activation='sigmoid' , name='output'))

In [159]:
len(model.weights)

6

In [160]:
len(model_2.weights)

4

In [161]:
model.summary()

Model: "sequential_19"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 hidden_1 (Dense)            (None, 8)                 96        
                                                                 
 hidden_2 (Dense)            (None, 6)                 54        
                                                                 
 output (Dense)              (None, 1)                 7         
                                                                 
Total params: 157
Trainable params: 157
Non-trainable params: 0
_________________________________________________________________


In [162]:
model_2.summary()

Model: "sequential_20"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 hidden_1 (Dense)            (None, 8)                 96        
                                                                 
 output (Dense)              (None, 1)                 9         
                                                                 
Total params: 105
Trainable params: 105
Non-trainable params: 0
_________________________________________________________________


In [163]:
model_2.compile(optimizer='adam',
                loss='binary_crossentropy',
                metrics=['accuracy'])

In [164]:
model_2.fit(scaled_x_train,y_train,epochs=100)

Epoch 1/100
219/219 [==============================] - 1s 1ms/step - loss: 0.6551 - accuracy: 0.6490
Epoch 2/100
219/219 [==============================] - 0s 1ms/step - loss: 0.5234 - accuracy: 0.7891
Epoch 3/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4656 - accuracy: 0.8009
Epoch 4/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4395 - accuracy: 0.8099
Epoch 5/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4269 - accuracy: 0.8174
Epoch 6/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4196 - accuracy: 0.8206
Epoch 7/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4132 - accuracy: 0.8239
Epoch 8/100
219/219 [==============================] - 0s 1ms/step - loss: 0.4068 - accuracy: 0.8269
Epoch 9/100
219/219 [==============================] - 0s 736us/step - loss: 0.4006 - accuracy: 0.8297
Epoch 10/100
219/219 [==============================] - 0s 834us/step - loss: 0.3942 - ac

In [165]:
y_pred_2 = model_2.predict(scaled_x_test)

94/94 [==============================] - 0s 638us/step


In [166]:
y_pred_2 = (y_ped_2  > 0.5)
y_pred_2

array([[False],
       [False],
       [False],
       ...,
       [False],
       [ True],
       [ True]])

In [167]:
model_2.evaluate(scaled_x_test,y_test)

94/94 [==============================] - 0s 809us/step - loss: 0.3301 - accuracy: 0.8633


[0.33013269305229187, 0.8633333444595337]

In [175]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix

In [169]:
con = confusion_matrix(y_test,y_pred_2)
con

array([[2271,  107],
       [ 311,  311]], dtype=int64)